callback Callback = void (Node node);

interface Node {
    void Node();
    attribute sequence<Node> children;
    sequence<Node> getChildren();
    void setChildren(sequence<Node> children_);
    Node eachBefore( Callback callback );
};